//! Keyboard event types and dispatch per RFC 0004 §7.4.
//!
//! Implements:
//! - `KeyDownEvent`   — physical key press (key_code + logical key + modifiers)
//! - `KeyUpEvent`     — physical key release
//! - `CharacterEvent` — post-IME committed Unicode character(s)
//! - `KeyboardModifiers` — bitfield for Shift/Ctrl/Alt/Meta/CapsLock/NumLock
//! - `KeyboardDispatch` — routing descriptor for key events (targeted node or tile)
//! - `KeyboardDispatchKind` — which payload to deliver
//! - `KeyboardProcessor` — translates raw OS key/char events + focus state into
//!   `KeyboardDispatch` descriptors for the owning agent.
//!
//! # Bubbling semantics (spec line 290)
//! Keyboard events target the focused node first. If the node does not consume
//! the event the caller may re-dispatch with a `KeyboardDispatch` whose `node_id`
//! is `None`, routing the event to the tile-level handler for the owning agent.
//!
//! # IME v1 fallback (spec lines 466–468)
//! In v1, only direct ASCII / basic Unicode input via `KeyDownEvent` and
//! `CharacterEvent` is mandatory. Full IME composition events are v1-reserved
//! (their protobuf schema is defined but Rust logic is not implemented here).
//!
//! # Spec refs
//! - Lines 289–291: Keyboard Event Types
//! - Lines 294–296: KeyDownEvent targets focused node
//! - Lines 298–300: Key events bubble to tile
//! - Lines 466–468: IME V1 Fallback

use serde::{Deserialize, Serialize};
use tze_hud_scene::{MonoUs, SceneId};

use crate::focus_tree::FocusOwner;

// ─── Modifier flags ────────────────────────────────────────────────────────────

/// Keyboard modifier state carried by key events (spec line 290).
///
/// Represented as a struct of boolean flags.
#[derive(Clone, Copy, Debug, Default, PartialEq, Eq, Serialize, Deserialize)]
pub struct KeyboardModifiers {
    pub shift: bool,
    pub ctrl: bool,
    pub alt: bool,
    pub meta: bool,
    /// CapsLock toggle state (not a momentary modifier).
    pub caps_lock: bool,
    /// NumLock toggle state.
    pub num_lock: bool,
}

impl KeyboardModifiers {
    /// No modifiers active.
    pub const NONE: Self = Self {
        shift: false,
        ctrl: false,
        alt: false,
        meta: false,
        caps_lock: false,
        num_lock: false,
    };
}

// ─── Raw OS keyboard event ─────────────────────────────────────────────────────

/// Raw key-down event from the OS (before focus routing).
///
/// `key_code` is the DOM `KeyboardEvent.code` string (physical key position,
/// e.g. `"KeyA"`, `"ArrowDown"`, `"ShiftLeft"`).
/// `key` is the DOM `KeyboardEvent.key` string (logical value after layout +
/// modifiers, e.g. `"a"`, `"A"`, `"ArrowDown"`).
///
/// Spec: lines 289–290.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RawKeyDownEvent {
    /// Physical key position (DOM `KeyboardEvent.code`).
    pub key_code: String,
    /// Logical key value (DOM `KeyboardEvent.key`).
    pub key: String,
    /// Active modifiers at the time of the event.
    pub modifiers: KeyboardModifiers,
    /// True if this event was generated by the OS key-repeat mechanism.
    pub repeat: bool,
    /// Monotonic timestamp in microseconds (hardware timestamp from winit).
    pub timestamp_mono_us: MonoUs,
}

/// Raw key-up event from the OS.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RawKeyUpEvent {
    pub key_code: String,
    pub key: String,
    pub modifiers: KeyboardModifiers,
    pub timestamp_mono_us: MonoUs,
}

/// Post-IME character event — committed Unicode text ready for insertion.
///
/// In v1 this is produced directly from OS character events when no IME is
/// active. Each event carries exactly the characters the OS committed (usually
/// a single codepoint, occasionally a multi-character string for ligatures /
/// precomposed sequences).
///
/// Spec: lines 290, 471–472.
#[derive(Clone, Debug, Serialize, Deserialize)]
pub struct RawCharacterEvent {
    /// Post-IME committed Unicode character(s).
    pub character: String,
    pub timestamp_mono_us: MonoUs,
}

// ─── Agent-facing event descriptors ──────────────────────────────────────────

/// Keyboard event to dispatch to the owning agent.
///
/// Generated by `KeyboardProcessor::process_key_down`,
/// `process_key_up`, and `process_character`.
#[derive(Clone, Debug)]
pub struct KeyboardDispatch {
    /// The agent namespace that should receive this event.
    pub namespace: String,
    /// Tile that holds focus (or whose tile-level handler should receive the event).
    pub tile_id: SceneId,
    /// Focused node, or `None` if the event has already bubbled to tile level.
    pub node_id: Option<SceneId>,
    /// Which event payload to deliver.
    pub kind: KeyboardDispatchKind,
}

/// The event payload carried by a `KeyboardDispatch`.
#[derive(Clone, Debug, PartialEq)]
pub enum KeyboardDispatchKind {
    KeyDown {
        key_code: String,
        key: String,
        modifiers: KeyboardModifiers,
        repeat: bool,
        timestamp_mono_us: MonoUs,
    },
    KeyUp {
        key_code: String,
        key: String,
        modifiers: KeyboardModifiers,
        timestamp_mono_us: MonoUs,
    },
    Character {
        character: String,
        timestamp_mono_us: MonoUs,
    },
}

// ─── Keyboard processor ───────────────────────────────────────────────────────

/// Translates raw OS keyboard events into `KeyboardDispatch` descriptors for the
/// owning agent, using the current focus state.
///
/// The processor is stateless with respect to focus (it takes the current
/// `FocusOwner` as a parameter); the `FocusManager` owns the focus state.
///
/// # Dispatch rules (spec lines 289–300)
/// 1. Keyboard events target the focused node first (`node_id = Some(...)`).
/// 2. If the node does not consume the event, the caller re-dispatches at tile
///    level by calling `bubble_to_tile`, which returns a new `KeyboardDispatch`
///    with `node_id = None`.
///
/// The caller (e.g. the runtime kernel's input loop) is responsible for:
/// - Passing consumed/unhandled results from agents back to `bubble_to_tile`.
/// - Routing the `KeyboardDispatch` to the correct agent session.
pub struct KeyboardProcessor;

impl KeyboardProcessor {
    pub fn new() -> Self {
        Self
    }

    /// Process a raw key-down event and produce a `KeyboardDispatch` if a
    /// node or tile has focus.
    ///
    /// Returns `None` if focus is `FocusOwner::None` or `ChromeElement`
    /// (chrome handles its own keyboard input).
    pub fn process_key_down(
        &self,
        event: &RawKeyDownEvent,
        focus: &FocusOwner,
        namespace_for_tile: impl Fn(SceneId) -> Option<String>,
    ) -> Option<KeyboardDispatch> {
        self.dispatch_to_focus(
            focus,
            namespace_for_tile,
            KeyboardDispatchKind::KeyDown {
                key_code: event.key_code.clone(),
                key: event.key.clone(),
                modifiers: event.modifiers,
                repeat: event.repeat,
                timestamp_mono_us: event.timestamp_mono_us,
            },
        )
    }

    /// Process a raw key-up event and produce a `KeyboardDispatch` if a
    /// node or tile has focus.
    pub fn process_key_up(
        &self,
        event: &RawKeyUpEvent,
        focus: &FocusOwner,
        namespace_for_tile: impl Fn(SceneId) -> Option<String>,
    ) -> Option<KeyboardDispatch> {
        self.dispatch_to_focus(
            focus,
            namespace_for_tile,
            KeyboardDispatchKind::KeyUp {
                key_code: event.key_code.clone(),
                key: event.key.clone(),
                modifiers: event.modifiers,
                timestamp_mono_us: event.timestamp_mono_us,
            },
        )
    }

    /// Process a post-IME character event and produce a `KeyboardDispatch` if a
    /// node or tile has focus.
    pub fn process_character(
        &self,
        event: &RawCharacterEvent,
        focus: &FocusOwner,
        namespace_for_tile: impl Fn(SceneId) -> Option<String>,
    ) -> Option<KeyboardDispatch> {
        self.dispatch_to_focus(
            focus,
            namespace_for_tile,
            KeyboardDispatchKind::Character {
                character: event.character.clone(),
                timestamp_mono_us: event.timestamp_mono_us,
            },
        )
    }

    /// Produce a tile-level re-dispatch for an event that the focused node did
    /// not consume (bubbling, spec line 298–300).
    ///
    /// Takes a `KeyboardDispatch` originally targeting a node and returns a new
    /// one targeting the tile (node_id = None). Returns `None` if the original
    /// dispatch was already tile-level.
    pub fn bubble_to_tile(&self, dispatch: KeyboardDispatch) -> Option<KeyboardDispatch> {
        dispatch.node_id?;
        Some(KeyboardDispatch {
            namespace: dispatch.namespace,
            tile_id: dispatch.tile_id,
            node_id: None,
            kind: dispatch.kind,
        })
    }

    // ─── Internal helpers ─────────────────────────────────────────────────

    fn dispatch_to_focus(
        &self,
        focus: &FocusOwner,
        namespace_for_tile: impl Fn(SceneId) -> Option<String>,
        kind: KeyboardDispatchKind,
    ) -> Option<KeyboardDispatch> {
        match focus {
            FocusOwner::None | FocusOwner::ChromeElement(_) => {
                // No agent focus; chrome handles its own events.
                None
            }
            FocusOwner::Tile(tile_id) => {
                let ns = namespace_for_tile(*tile_id)?;
                Some(KeyboardDispatch {
                    namespace: ns,
                    tile_id: *tile_id,
                    node_id: None,
                    kind,
                })
            }
            FocusOwner::Node { tile_id, node_id } => {
                let ns = namespace_for_tile(*tile_id)?;
                Some(KeyboardDispatch {
                    namespace: ns,
                    tile_id: *tile_id,
                    node_id: Some(*node_id),
                    kind,
                })
            }
        }
    }
}

impl Default for KeyboardProcessor {
    fn default() -> Self {
        Self::new()
    }
}

// ─── Tests ─────────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;
    use tze_hud_scene::SceneId;

    fn make_key_down(key_code: &str, key: &str) -> RawKeyDownEvent {
        RawKeyDownEvent {
            key_code: key_code.to_string(),
            key: key.to_string(),
            modifiers: KeyboardModifiers::NONE,
            repeat: false,
            timestamp_mono_us: MonoUs(1_000),
        }
    }

    fn make_key_up(key_code: &str, key: &str) -> RawKeyUpEvent {
        RawKeyUpEvent {
            key_code: key_code.to_string(),
            key: key.to_string(),
            modifiers: KeyboardModifiers::NONE,
            timestamp_mono_us: MonoUs(2_000),
        }
    }

    fn make_char(ch: &str) -> RawCharacterEvent {
        RawCharacterEvent {
            character: ch.to_string(),
            timestamp_mono_us: MonoUs(1_500),
        }
    }

    // ── WHEN node N1 in tile T1 has focus THEN agent receives KeyDownEvent ──

    /// Spec scenario (line 295): focused node receives KeyDownEvent.
    #[test]
    fn key_down_dispatched_to_focused_node() {
        let tile_id = SceneId::new();
        let node_id = SceneId::new();
        let focus = FocusOwner::Node { tile_id, node_id };
        let proc = KeyboardProcessor::new();

        let dispatch = proc
            .process_key_down(&make_key_down("KeyA", "a"), &focus, |_| {
                Some("agent-ns".to_string())
            })
            .expect("expected KeyboardDispatch for focused node");

        assert_eq!(dispatch.namespace, "agent-ns");
        assert_eq!(dispatch.tile_id, tile_id);
        assert_eq!(dispatch.node_id, Some(node_id));

        match dispatch.kind {
            KeyboardDispatchKind::KeyDown {
                key_code,
                key,
                repeat,
                ..
            } => {
                assert_eq!(key_code, "KeyA");
                assert_eq!(key, "a");
                assert!(!repeat);
            }
            _ => panic!("expected KeyDown kind"),
        }
    }

    /// Spec scenario (line 295): focused node receives CharacterEvent.
    #[test]
    fn character_dispatched_to_focused_node() {
        let tile_id = SceneId::new();
        let node_id = SceneId::new();
        let focus = FocusOwner::Node { tile_id, node_id };
        let proc = KeyboardProcessor::new();

        let dispatch = proc
            .process_character(&make_char("a"), &focus, |_| Some("agent-ns".to_string()))
            .expect("expected CharacterDispatch for focused node");

        assert_eq!(dispatch.node_id, Some(node_id));
        match dispatch.kind {
            KeyboardDispatchKind::Character { character, .. } => {
                assert_eq!(character, "a");
            }
            _ => panic!("expected Character kind"),
        }
    }

    /// IME v1 mandatory: CharacterEvent for basic Unicode (spec line 472).
    #[test]
    fn character_event_basic_unicode() {
        let tile_id = SceneId::new();
        let node_id = SceneId::new();
        let focus = FocusOwner::Node { tile_id, node_id };
        let proc = KeyboardProcessor::new();

        // Unicode character beyond ASCII
        let dispatch = proc
            .process_character(
                &RawCharacterEvent {
                    character: "é".to_string(),
                    timestamp_mono_us: MonoUs(100),
                },
                &focus,
                |_| Some("ns".to_string()),
            )
            .expect("unicode character should dispatch");

        match dispatch.kind {
            KeyboardDispatchKind::Character { character, .. } => assert_eq!(character, "é"),
            _ => panic!("expected Character kind"),
        }
    }

    /// Key-up dispatched to focused node.
    #[test]
    fn key_up_dispatched_to_focused_node() {
        let tile_id = SceneId::new();
        let node_id = SceneId::new();
        let focus = FocusOwner::Node { tile_id, node_id };
        let proc = KeyboardProcessor::new();

        let dispatch = proc
            .process_key_up(&make_key_up("KeyA", "a"), &focus, |_| {
                Some("agent-ns".to_string())
            })
            .expect("expected KeyUpDispatch for focused node");

        assert_eq!(dispatch.node_id, Some(node_id));
        match dispatch.kind {
            KeyboardDispatchKind::KeyUp { key_code, .. } => assert_eq!(key_code, "KeyA"),
            _ => panic!("expected KeyUp kind"),
        }
    }

    /// Spec scenario (line 298–300): key event bubbles to tile if node doesn't consume.
    #[test]
    fn key_event_bubbles_to_tile() {
        let tile_id = SceneId::new();
        let node_id = SceneId::new();
        let focus = FocusOwner::Node { tile_id, node_id };
        let proc = KeyboardProcessor::new();

        let dispatch = proc
            .process_key_down(&make_key_down("KeyB", "b"), &focus, |_| {
                Some("agent-ns".to_string())
            })
            .expect("initial dispatch to node");

        assert_eq!(
            dispatch.node_id,
            Some(node_id),
            "initial dispatch targets node"
        );

        // Node did not consume — bubble to tile.
        let bubbled = proc
            .bubble_to_tile(dispatch)
            .expect("bubble_to_tile should return tile-level dispatch");

        assert_eq!(bubbled.node_id, None, "bubbled dispatch has no node_id");
        assert_eq!(bubbled.tile_id, tile_id);
        assert_eq!(bubbled.namespace, "agent-ns");
    }

    /// Bubbling at tile-level dispatch returns None (nothing further to bubble to).
    #[test]
    fn bubble_from_tile_level_returns_none() {
        let tile_id = SceneId::new();
        let focus = FocusOwner::Tile(tile_id);
        let proc = KeyboardProcessor::new();

        let dispatch = proc
            .process_key_down(&make_key_down("KeyC", "c"), &focus, |_| {
                Some("ns".to_string())
            })
            .expect("tile-level dispatch");

        assert_eq!(dispatch.node_id, None);
        assert!(proc.bubble_to_tile(dispatch).is_none());
    }

    /// No dispatch when focus is None.
    #[test]
    fn no_dispatch_when_focus_is_none() {
        let focus = FocusOwner::None;
        let proc = KeyboardProcessor::new();
        assert!(
            proc.process_key_down(&make_key_down("KeyA", "a"), &focus, |_| Some(
                "ns".to_string()
            ))
            .is_none()
        );
    }

    /// No dispatch when focus is on a chrome element.
    #[test]
    fn no_dispatch_when_focus_is_chrome() {
        let chrome_id = SceneId::new();
        let focus = FocusOwner::ChromeElement(chrome_id);
        let proc = KeyboardProcessor::new();
        assert!(
            proc.process_key_down(&make_key_down("KeyA", "a"), &focus, |_| Some(
                "ns".to_string()
            ))
            .is_none()
        );
    }

    /// Tile-level focus routes to tile (node_id = None).
    #[test]
    fn tile_focus_routes_to_tile() {
        let tile_id = SceneId::new();
        let focus = FocusOwner::Tile(tile_id);
        let proc = KeyboardProcessor::new();

        let dispatch = proc
            .process_key_down(&make_key_down("Enter", "Enter"), &focus, |_| {
                Some("agent".to_string())
            })
            .expect("tile-level dispatch");

        assert_eq!(dispatch.tile_id, tile_id);
        assert_eq!(dispatch.node_id, None);
    }

    /// Repeat flag is preserved.
    #[test]
    fn repeat_flag_preserved() {
        let tile_id = SceneId::new();
        let node_id = SceneId::new();
        let focus = FocusOwner::Node { tile_id, node_id };
        let proc = KeyboardProcessor::new();

        let repeat_event = RawKeyDownEvent {
            key_code: "ArrowDown".to_string(),
            key: "ArrowDown".to_string(),
            modifiers: KeyboardModifiers::NONE,
            repeat: true,
            timestamp_mono_us: MonoUs(5_000),
        };

        let dispatch = proc
            .process_key_down(&repeat_event, &focus, |_| Some("ns".to_string()))
            .expect("repeat key dispatch");

        match dispatch.kind {
            KeyboardDispatchKind::KeyDown { repeat, .. } => assert!(repeat),
            _ => panic!("expected KeyDown"),
        }
    }

    /// Modifiers are preserved in the dispatch.
    #[test]
    fn modifiers_preserved() {
        let tile_id = SceneId::new();
        let node_id = SceneId::new();
        let focus = FocusOwner::Node { tile_id, node_id };
        let proc = KeyboardProcessor::new();

        let event = RawKeyDownEvent {
            key_code: "KeyS".to_string(),
            key: "S".to_string(),
            modifiers: KeyboardModifiers {
                shift: true,
                ctrl: true,
                ..KeyboardModifiers::NONE
            },
            repeat: false,
            timestamp_mono_us: MonoUs(200),
        };

        let dispatch = proc
            .process_key_down(&event, &focus, |_| Some("ns".to_string()))
            .expect("dispatch");

        match dispatch.kind {
            KeyboardDispatchKind::KeyDown { modifiers, .. } => {
                assert!(modifiers.shift);
                assert!(modifiers.ctrl);
                assert!(!modifiers.alt);
            }
            _ => panic!("expected KeyDown"),
        }
    }

    /// Timestamp is preserved in the dispatch.
    #[test]
    fn timestamp_preserved_in_key_down() {
        let tile_id = SceneId::new();
        let node_id = SceneId::new();
        let focus = FocusOwner::Node { tile_id, node_id };
        let proc = KeyboardProcessor::new();

        let dispatch = proc
            .process_key_down(
                &RawKeyDownEvent {
                    key_code: "Space".to_string(),
                    key: " ".to_string(),
                    modifiers: KeyboardModifiers::NONE,
                    repeat: false,
                    timestamp_mono_us: MonoUs(99_999),
                },
                &focus,
                |_| Some("ns".to_string()),
            )
            .unwrap();

        match dispatch.kind {
            KeyboardDispatchKind::KeyDown {
                timestamp_mono_us, ..
            } => {
                assert_eq!(timestamp_mono_us, MonoUs(99_999));
            }
            _ => panic!(),
        }
    }
}
