//! # Event Taxonomy
//!
//! Three-category event taxonomy per scene-events/spec.md §1.1–§1.2.
//!
//! All events are classified into exactly three categories:
//! - **Input** — governed by RFC 0004 (pointer, keyboard, gesture, focus).
//! - **Scene** — runtime-generated observations of scene-graph mutations.
//! - **System** — runtime-internal (lease, degradation, telemetry, attention).
//!
//! Each `SceneEvent` variant belongs to exactly one `EventCategory`, which
//! maps to exactly one `SubscriptionCategory`.

use serde::{Deserialize, Serialize};

// ─── Top-level category ──────────────────────────────────────────────────────

/// The three top-level categories every event belongs to.
///
/// Spec: scene-events/spec.md lines 5-17, Requirement: Three-Category Event Taxonomy.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum EventCategory {
    /// Input events owned by RFC 0004 (pointer, keyboard, gesture, focus).
    /// Delivered only to the agent that owns the target tile.
    Input,
    /// Scene events generated by the compositor on scene-graph mutations.
    /// Delivered to agents subscribed to the appropriate scene category.
    Scene,
    /// System events generated by the runtime kernel (lease, degradation,
    /// telemetry, attention). Always delivered for mandatory categories.
    System,
}

// ─── Subscription categories ─────────────────────────────────────────────────

/// The nine subscription categories agents use to filter event delivery.
///
/// Spec: scene-events/spec.md lines 156-184, Requirement: Subscription Model
/// with Category Filtering.
///
/// Category-to-event-type-prefix mapping:
///
/// | Category              | Event type prefix pattern |
/// |-----------------------|--------------------------|
/// | `SceneTopology`       | `scene.*`                |
/// | `InputEvents`         | `input.*`                |
/// | `FocusEvents`         | `scene.focus.*`          |
/// | `DegradationNotices`  | `system.degradation_*`   |
/// | `LeaseChanges`        | `system.lease_*`         |
/// | `ZoneEvents`          | `scene.zone.*`           |
/// | `TelemetryFrames`     | `system.telemetry_*`     |
/// | `AttentionEvents`     | `system.attention_*`     |
/// | `AgentEvents`         | `agent.*`                |
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, Serialize, Deserialize)]
pub enum SubscriptionCategory {
    /// All scene topology changes: tile create/delete, tab create, agent join.
    /// Prefix: `scene.*`. Maps to `EventCategory::Scene`.
    SceneTopology,
    /// Input events (RFC 0004): pointer, keyboard, gesture.
    /// Prefix: `input.*`. Maps to `EventCategory::Input`.
    InputEvents,
    /// Focus events: gained, lost.
    /// Prefix: `scene.focus.*`. Maps to `EventCategory::Scene`.
    FocusEvents,
    /// Degradation level notifications. **Cannot be opted out of.**
    /// Prefix: `system.degradation_*`. Maps to `EventCategory::System`.
    DegradationNotices,
    /// Lease lifecycle events. **Cannot be opted out of.**
    /// Prefix: `system.lease_*`. Maps to `EventCategory::System`.
    LeaseChanges,
    /// Zone state events: occupancy changes, publish results.
    /// Prefix: `scene.zone.*`. Maps to `EventCategory::Scene`.
    ZoneEvents,
    /// Telemetry frame snapshots.
    /// Prefix: `system.telemetry_*`. Maps to `EventCategory::System`.
    TelemetryFrames,
    /// Reserved category; the runtime currently emits no `system.attention_*` events.
    /// Prefix: `system.attention_*`. Maps to `EventCategory::System`.
    AttentionEvents,
    /// Agent-emitted events (prefixed with `agent.<namespace>.`).
    /// Prefix: `agent.*`. Maps to `EventCategory::Scene` (agent-observable).
    AgentEvents,
}

impl SubscriptionCategory {
    /// Whether agents can opt out of this category.
    ///
    /// `DegradationNotices` and `LeaseChanges` are mandatory; all others are
    /// optional and filtered by the agent's granted capabilities.
    pub fn is_mandatory(self) -> bool {
        matches!(
            self,
            SubscriptionCategory::DegradationNotices | SubscriptionCategory::LeaseChanges
        )
    }

    /// The event type prefix pattern that routes into this category.
    ///
    /// Trailing `*` matches any suffix with the same initial segment(s).
    pub fn event_type_prefix(self) -> &'static str {
        match self {
            SubscriptionCategory::SceneTopology => "scene.",
            SubscriptionCategory::InputEvents => "input.",
            SubscriptionCategory::FocusEvents => "scene.focus.",
            SubscriptionCategory::DegradationNotices => "system.degradation_",
            SubscriptionCategory::LeaseChanges => "system.lease_",
            SubscriptionCategory::ZoneEvents => "scene.zone.",
            SubscriptionCategory::TelemetryFrames => "system.telemetry_",
            SubscriptionCategory::AttentionEvents => "system.attention_",
            SubscriptionCategory::AgentEvents => "agent.",
        }
    }

    /// The top-level `EventCategory` this subscription category belongs to.
    pub fn event_category(self) -> EventCategory {
        match self {
            SubscriptionCategory::SceneTopology
            | SubscriptionCategory::FocusEvents
            | SubscriptionCategory::ZoneEvents
            | SubscriptionCategory::AgentEvents => EventCategory::Scene,
            SubscriptionCategory::InputEvents => EventCategory::Input,
            SubscriptionCategory::DegradationNotices
            | SubscriptionCategory::LeaseChanges
            | SubscriptionCategory::TelemetryFrames
            | SubscriptionCategory::AttentionEvents => EventCategory::System,
        }
    }

    /// Return the subscription category that delivers a given event type, if any.
    ///
    /// An event type that matches no subscription category is not routable.
    /// Prefer the most specific match: `scene.focus.*` before `scene.*`.
    pub fn for_event_type(event_type: &str) -> Option<Self> {
        // Test most-specific prefixes first.
        if event_type.starts_with("scene.focus.") {
            return Some(SubscriptionCategory::FocusEvents);
        }
        if event_type.starts_with("scene.zone.") {
            return Some(SubscriptionCategory::ZoneEvents);
        }
        if event_type.starts_with("scene.") {
            return Some(SubscriptionCategory::SceneTopology);
        }
        if event_type.starts_with("input.") {
            return Some(SubscriptionCategory::InputEvents);
        }
        if event_type.starts_with("system.degradation_") {
            return Some(SubscriptionCategory::DegradationNotices);
        }
        if event_type.starts_with("system.lease_") {
            return Some(SubscriptionCategory::LeaseChanges);
        }
        if event_type.starts_with("system.telemetry_") {
            return Some(SubscriptionCategory::TelemetryFrames);
        }
        if event_type.starts_with("system.attention_") {
            return Some(SubscriptionCategory::AttentionEvents);
        }
        if event_type.starts_with("agent.") {
            return Some(SubscriptionCategory::AgentEvents);
        }
        None
    }
}

// ─── Tests ───────────────────────────────────────────────────────────────────

#[cfg(test)]
mod tests {
    use super::*;

    /// WHEN any event is generated THEN it must map to exactly one subscription
    /// category (spec lines 11-12).
    #[test]
    fn scene_tile_created_routes_to_scene_topology() {
        let cat = SubscriptionCategory::for_event_type("scene.tile.created");
        assert_eq!(cat, Some(SubscriptionCategory::SceneTopology));
    }

    #[test]
    fn scene_zone_occupancy_changed_routes_to_zone_events() {
        // ZoneOccupancyChanged appears in BOTH SceneTopology and ZoneEvents.
        // `for_event_type` returns ZoneEvents (most specific match).
        // Dual routing with deduplication is handled by the event bus (bead #2).
        let cat = SubscriptionCategory::for_event_type("scene.zone.occupancy_changed");
        assert_eq!(cat, Some(SubscriptionCategory::ZoneEvents));
    }

    #[test]
    fn scene_focus_changed_routes_to_focus_events() {
        let cat = SubscriptionCategory::for_event_type("scene.focus.changed");
        assert_eq!(cat, Some(SubscriptionCategory::FocusEvents));
    }

    #[test]
    fn system_degradation_changed_routes_to_degradation_notices() {
        let cat = SubscriptionCategory::for_event_type("system.degradation_changed");
        assert_eq!(cat, Some(SubscriptionCategory::DegradationNotices));
    }

    #[test]
    fn system_lease_revoked_routes_to_lease_changes() {
        let cat = SubscriptionCategory::for_event_type("system.lease_revoked");
        assert_eq!(cat, Some(SubscriptionCategory::LeaseChanges));
    }

    #[test]
    fn agent_event_routes_to_agent_events() {
        let cat = SubscriptionCategory::for_event_type("agent.doorbell_agent.doorbell.ring");
        assert_eq!(cat, Some(SubscriptionCategory::AgentEvents));
    }

    #[test]
    fn input_event_routes_to_input_events() {
        let cat = SubscriptionCategory::for_event_type("input.pointer.down");
        assert_eq!(cat, Some(SubscriptionCategory::InputEvents));
    }

    #[test]
    fn unknown_event_type_has_no_category() {
        let cat = SubscriptionCategory::for_event_type("unknown.event.type");
        assert_eq!(cat, None);
    }

    #[test]
    fn mandatory_categories_cannot_be_opted_out() {
        assert!(SubscriptionCategory::DegradationNotices.is_mandatory());
        assert!(SubscriptionCategory::LeaseChanges.is_mandatory());
    }

    #[test]
    fn non_mandatory_categories_are_optional() {
        assert!(!SubscriptionCategory::SceneTopology.is_mandatory());
        assert!(!SubscriptionCategory::AgentEvents.is_mandatory());
        assert!(!SubscriptionCategory::InputEvents.is_mandatory());
        assert!(!SubscriptionCategory::FocusEvents.is_mandatory());
        assert!(!SubscriptionCategory::ZoneEvents.is_mandatory());
        assert!(!SubscriptionCategory::TelemetryFrames.is_mandatory());
        assert!(!SubscriptionCategory::AttentionEvents.is_mandatory());
    }

    #[test]
    fn subscription_category_has_correct_top_level_category() {
        assert_eq!(
            SubscriptionCategory::SceneTopology.event_category(),
            EventCategory::Scene
        );
        assert_eq!(
            SubscriptionCategory::InputEvents.event_category(),
            EventCategory::Input
        );
        assert_eq!(
            SubscriptionCategory::DegradationNotices.event_category(),
            EventCategory::System
        );
        assert_eq!(
            SubscriptionCategory::LeaseChanges.event_category(),
            EventCategory::System
        );
        assert_eq!(
            SubscriptionCategory::AgentEvents.event_category(),
            EventCategory::Scene
        );
    }
}
