# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import session_pb2 as session__pb2

GRPC_GENERATED_VERSION = '1.80.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in session_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class HudSessionStub(object):
    """─── Session Protocol ─────────────────────────────────────────────────────────

    Bidirectional streaming session protocol for resident agent <-> runtime
    communication. Implements RFC 0005 (Session/Protocol).

    This replaces the unary-RPC model in SceneService with a single
    multiplexed bidirectional stream per agent.

    ID convention: All scene-object IDs use `bytes` (16-byte UUIDv7).
    Future: import from common/ids.proto once SceneId message is extracted.

    ─── gRPC service ─────────────────────────────────────────────────────────────

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/tze_hud.protocol.v1.session.HudSession/Session',
                request_serializer=session__pb2.ClientMessage.SerializeToString,
                response_deserializer=session__pb2.ServerMessage.FromString,
                _registered_method=True)


class HudSessionServicer(object):
    """─── Session Protocol ─────────────────────────────────────────────────────────

    Bidirectional streaming session protocol for resident agent <-> runtime
    communication. Implements RFC 0005 (Session/Protocol).

    This replaces the unary-RPC model in SceneService with a single
    multiplexed bidirectional stream per agent.

    ID convention: All scene-object IDs use `bytes` (16-byte UUIDv7).
    Future: import from common/ids.proto once SceneId message is extracted.

    ─── gRPC service ─────────────────────────────────────────────────────────────

    """

    def Session(self, request_iterator, context):
        """Primary bidirectional session stream.
        All session traffic (handshake, mutations, events, heartbeats,
        lease management, subscriptions) flows over this single stream.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_HudSessionServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=session__pb2.ClientMessage.FromString,
                    response_serializer=session__pb2.ServerMessage.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tze_hud.protocol.v1.session.HudSession', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tze_hud.protocol.v1.session.HudSession', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class HudSession(object):
    """─── Session Protocol ─────────────────────────────────────────────────────────

    Bidirectional streaming session protocol for resident agent <-> runtime
    communication. Implements RFC 0005 (Session/Protocol).

    This replaces the unary-RPC model in SceneService with a single
    multiplexed bidirectional stream per agent.

    ID convention: All scene-object IDs use `bytes` (16-byte UUIDv7).
    Future: import from common/ids.proto once SceneId message is extracted.

    ─── gRPC service ─────────────────────────────────────────────────────────────

    """

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/tze_hud.protocol.v1.session.HudSession/Session',
            session__pb2.ClientMessage.SerializeToString,
            session__pb2.ServerMessage.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class RuntimeServiceStub(object):
    """─── RuntimeService — configuration management RPC ────────────────────────────

    Implements RFC 0006 §9 (v1-mandatory): live configuration reload without
    process restart. The `ReloadConfig` RPC is one of the two required triggers
    for hot-reloadable config sections ([privacy], [degradation], [chrome],
    [agents.dynamic_policy]). The other trigger is SIGHUP (OS signal).

    Callers must supply the full TOML config; the runtime re-validates the entire
    file and applies only the hot-reloadable sections on success.

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ReloadConfig = channel.unary_unary(
                '/tze_hud.protocol.v1.session.RuntimeService/ReloadConfig',
                request_serializer=session__pb2.ReloadConfigRequest.SerializeToString,
                response_deserializer=session__pb2.ReloadConfigResponse.FromString,
                _registered_method=True)


class RuntimeServiceServicer(object):
    """─── RuntimeService — configuration management RPC ────────────────────────────

    Implements RFC 0006 §9 (v1-mandatory): live configuration reload without
    process restart. The `ReloadConfig` RPC is one of the two required triggers
    for hot-reloadable config sections ([privacy], [degradation], [chrome],
    [agents.dynamic_policy]). The other trigger is SIGHUP (OS signal).

    Callers must supply the full TOML config; the runtime re-validates the entire
    file and applies only the hot-reloadable sections on success.

    """

    def ReloadConfig(self, request, context):
        """Reload hot-reloadable configuration sections from a new TOML string.

        The runtime validates the supplied TOML. If validation succeeds, the
        hot-reloadable sections ([privacy], [degradation], [chrome],
        [agents.dynamic_policy]) are atomically applied. Frozen sections
        ([runtime], [[tabs]], [agents.registered]) are silently ignored.

        Returns:
        - ReloadConfigResponse with success=true on successful reload.
        - ReloadConfigResponse with success=false and validation_errors populated
        on parse or validation failure. The running config is NOT modified.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_RuntimeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ReloadConfig': grpc.unary_unary_rpc_method_handler(
                    servicer.ReloadConfig,
                    request_deserializer=session__pb2.ReloadConfigRequest.FromString,
                    response_serializer=session__pb2.ReloadConfigResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'tze_hud.protocol.v1.session.RuntimeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('tze_hud.protocol.v1.session.RuntimeService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class RuntimeService(object):
    """─── RuntimeService — configuration management RPC ────────────────────────────

    Implements RFC 0006 §9 (v1-mandatory): live configuration reload without
    process restart. The `ReloadConfig` RPC is one of the two required triggers
    for hot-reloadable config sections ([privacy], [degradation], [chrome],
    [agents.dynamic_policy]). The other trigger is SIGHUP (OS signal).

    Callers must supply the full TOML config; the runtime re-validates the entire
    file and applies only the hot-reloadable sections on success.

    """

    @staticmethod
    def ReloadConfig(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/tze_hud.protocol.v1.session.RuntimeService/ReloadConfig',
            session__pb2.ReloadConfigRequest.SerializeToString,
            session__pb2.ReloadConfigResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
